spring:
  main:
    web-application-type: REACTIVE
  application:
    name: api-gateway
  security:
    secretKey: 6WGfy+zHxnaLCSYEtbok2NqyezDDZg0aMMcifl6rNKuSi5/xXMvJCBuiPjiT61iaRoWMzkC16Jv881Zpa5GRJCyRaF1hZzBRU7EDaEDMJpqhXskf8Vi2siskAyV9gzKDdjJEMrCk+qT5JO+EdVOM85jhQm5DNMvjP5O36cZZ+D7Wurh/1c9/5uObrrnN30zBechQ/dcqDz9j5LkojXzlNZJC+WfSyyLElOH6Vw==

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    restart:
      enabled: true

spring.cloud.gateway:
  permitAll: "${PERMIT_ALL_WHITELIST: /actuator/**, /api/demo/account/hello, /api/demo/account/login}"
  httpclient:
    wiretap: false
  httpserver:
    wiretap: false

  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

  globalcors:
    corsConfigurations:
      '[/**]':
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
  routes:
    - id: demo-account
      uri: http://localhost:8090
      predicates:
        - Path=/api/demo/account/**
      filters:
        - RewritePath=/api/demo/account(?<segment>/?.*), /api/account$\{segment}

logging:
  level:
    reactor.netty.http.client: WARN
    io.netty.handler.codec.http: WARN
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE